### ISSUE TITLE
Document does not have a meta description !?

### ISSUE THREAD

**Issue by ksorv** [hankchizljaw/hylia#109]
On auditing [hylia](https://hylia.website/) over Lighthouse, I found out that the SEO score is 91.

One thing that's causing this is: 

No `<meta name="Description" content="This is hylia description!">`

Please add the same or I can open a PR!

Ohhh and adding this makes the SEO -> 100!!!  😎

**Comment by hankchizljaw** [comment]
The meta description is controlled by the metaDescription frontmatter on all pages 👍

**Comment by ksorv** [comment]
Then I'd suggest that you add that onto the pages of hylia.website as that is the official website for this starter. 
Thanks for this great kit.  🍻
