### ISSUE TITLE
Docs: Incorrect link to the design tokens course

### ISSUE THREAD

**Issue by juanfernandes** [hankchizljaw/hylia#33]
Where Jina is thanked for her work on design token, there is a link to a course, but it takes you to twitter - should it be link to this: https://aycl.uie.com/virtual_seminars/design_tokens_scaling_design_with_a_single_source_of_truth

Or should the text be changed to say 'follow Jina on twitter' or something along those lines?

**Comment by andybelldesign** [comment]
Ah good catch @juanfernandes!! Yeh that's exactly where is should point. Fancy running a PR?

**Comment by juanfernandes** [comment]
Yeah, more than happyt to do a PR

**Comment by andybelldesign** [comment]
Awesome, thank you!
