### ISSUE TITLE
No license file? 

### ISSUE THREAD

**Issue by dberesford** [hankchizljaw/hylia#79]
MIT is referenced in package.json (https://github.com/andybelldesign/hylia/blob/545a697bab0efa2cbd9726cc6a3914d4f9ecd943/package.json#L46) but any reason there's no explicit LICENSE file in the repo. Happy to PR one

**Comment by andybelldesign** [comment]
Ah yes, good catch. A PR would be much appreciated, thank you.

**Comment by dberesford** [comment]
Gladly - https://github.com/andybelldesign/hylia/pull/80
Feel free to tweak the copyright as you see fit :-)
