### ISSUE TITLE
Generic page renders as source code

### ISSUE THREAD

**Issue by adamsilver** [hankchizljaw/hylia#81]
What I did:

1. Create a new Hylia site
2. Enabled the Git identity to be able to login to the CMS
3. Made a new Generic Page
4. Published it

And it renders the source code which you can [see here](https://inspiring-yalow-4e8488.netlify.com/another):

![image](https://user-images.githubusercontent.com/37163/65311294-f476b900-db87-11e9-9e99-df687846b253.png)

**Comment by hankchizljaw** [comment]
Cracked it! A bit of a weird one, but here it is:

When you set the permalink like this `/testing-123` which is the intuitive way to do it, Eleventy appears to render it as a file. The browser then just treats it as a text file.

The solution is to do `/testing-123.html` instead...

https://lucid-bhabha-061e53.netlify.com/testing-123/

What I’ll do is try to add some helper text in the CMS for that field _and_ remove the required state.

Cheers for uncovering this one, Adam.

**Comment by adamsilver** [comment]
Immense, thanks!
