### ISSUE TITLE
Slate color definition is missing from config.yml

### ISSUE THREAD

**Issue by MrJean** [hankchizljaw/hylia#87]
I've noticed that the Slate color definition is missing from config.yml so it can be used in the admin panel. This results in Slate not being adopted as a token and not being available for Sass / CSS Variables to use. I can provide a PR with a fix is this is OK.

PS. Thanks for the great starter! I started using it yesterday and I'm loving it so far.

**Comment by hankchizljaw** [comment]
Good catch! Yes please, a PR would be great!

**Comment by MrJean** [comment]
Closing this issue, since solution is merged.
