### ISSUE TITLE
Forestry Remote Login Integration

### ISSUE THREAD

**Issue by djmtype** [hankchizljaw/hylia#96]
I installed Hylia, choosing it as one of Forestry's 11ty starter templates. I then set up an admin, setting the path to `/portal` instead of the default, `/admin`, because `admin` in this theme refers to Netlify CMS. 

I see a `portal` directory set up in the root of my project, and `admin_path: "/portal"` specified under `.forestry > settings.yaml`.

I'm using Netlify for deployment only, and my url is https://hylia-forest.netlify.com. So, by visiting [https://hylia-forest.netlify.com/portal](https://hylia-forest.netlify.com), I expected to see a Forestry remote login for my site as picture here: https://forestry.io/docs/editing/remote-admin/, but instead receive a 404. 

So, what is the best way to integrate this?

**Comment by DirtyF** [comment]
👋 Hi, 

The Forestry starter is based on [a fork of this repository/](https://github.com/DirtyF/hylia-forestry). I shall update it. In the time being:

-  remote admin folder should be in `src/portal/` make sure this folder is 
- `src/portal/index.html` should use PassthroughCopy in Eleventy config's file (see https://github.com/hankchizljaw/hylia/blob/master/.eleventy.js#L34-L35 for an example)

Feel free to close this issue, as it's not related to the original starter. Thanks.

**Comment by djmtype** [comment]
Thanks @DirtyF I'll close this issue here and open it on your repo.

**Comment by djmtype** [comment]
@DirtyF BTW, you have Issues disabled on your repo.
