### ISSUE TITLE
Globals/Site Data not saving in Netlify CMS

### ISSUE THREAD

**Issue by pixelpony** [hankchizljaw/hylia#98]
Likely not something for you to fix, but figured you might want to know about the issue:

https://community.netlify.com/t/github-error-on-save-in-netlify-cms/7112

I will update here if/when I get follow-up from Netlify community.

**Comment by hankchizljaw** [comment]
Huh, that's a weird one. Yeh let’s keep an eye on that. Thank you, @pixelpony

**Comment by pixelpony** [comment]
Yeah, I actually effed up the inital report. It's "Globals/Site Data" not "Globals/Globals" that's not publishing. There goes my one theory. Updated my post on netlify community.

**Comment by pixelpony** [comment]
Transient error, apparently. Github stopped complaining.
